project_name: gnmic
builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/karimra/gnmic/app.version={{.Version}} -X github.com/karimra/gnmic/app.commit={{.ShortCommit}} -X github.com/karimra/gnmic/app.date={{.Date}} -X github.com/karimra/gnmic/app.gitURL={{.GitURL}}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    hooks:
      post: upx "{{ .Path }}"
dockers:
  - goos: linux
    goarch: amd64
    binaries:
      - gnmic
    image_templates:
      - "docker.io/gnmic/gnmic:latest"
      - 'docker.io/gnmic/gnmic:{{ replace .Version "v" ""}}'
      - "ghcr.io/karimra/gnmic:latest"
      - 'ghcr.io/karimra/gnmic:{{ replace .Version "v" ""}}'
    dockerfile: goreleaser.dockerfile
    skip_push: false
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      amd64: x86_64
      386: i386
      arm: armv7
      arm64: aarch64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}"
publishers:
  - name: fury.io deb/rpm packages
    ids:
      - gnmic # this id belongs to nfpm section and is used to only upload artifacts from nfpm
    dir: "{{ dir .ArtifactPath }}"
    cmd: curl -F package=@{{ .ArtifactName }} https://{{ .Env.FURY_TOKEN }}@push.fury.io/netdevops/
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

nfpms:
  - id: gnmic
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      amd64: x86_64
      386: i386
      darwin: Darwin
      linux: Linux
    vendor: gnmic
    homepage: https://gnmic.kmrd.dev
    maintainer: Karim Radhouani <medkarimrdi@gmail.com>, Roman Dodin <dodin.roman@gmail.com>
    description: gNMI CLI client and collector
    license: Apache 2.0
    formats:
      - deb
      - rpm
    bindir: /usr/local/bin
